### ISSUE TITLE
New Game

### ISSUE THREAD

**Issue by danielgwj** [cs361-W16/Group11-2#1]
There is no new game function as of yet.

"New Game" will be made into a clickable button.
The button then resets the game to a new state.

**Comment by danielgwj** [comment]
There is a liability on my New Game function:

I will need the CardsLeft and Score function so I can reset the values during the new game.

**Comment by matsuish** [comment]
Sorry for answering late.
I implemented score part. I simply added member valuable "score" in game class. score is just updated when a card is removed. when new game is started, just set score=0. Thanks,

**Comment by danielgwj** [comment]
Thanks for adding the score in the game class, I have added that the score would reset when the new game button is pressed.

**Comment by danielgwj** [comment]
Since Game state is reinitialized every time, there is no need to set these values to zero.

Issue closed
