### ISSUE TITLE
Spanish Game

### ISSUE THREAD

**Issue by danielgwj** [cs361-W16/Group11-2#15]
Game with Spanish rules is not up yet.
- A Spanish Game Class will be made and inherited from the abstract Game Class

**Comment by danielgwj** [comment]
@matsuish Shotaro!
We have something to discuss regarding our inheritance class.

Since we will be inheriting the abstract class "Game" I am suggesting that we take out the score and cardsLeft value assigning out of the Game constructor, e.g. public Game()

It will look something like this

```
    public int score = 0;
    public int cardsLeft = 0;

    public Game(){
        cols.add(new ArrayList<Card>());
        cols.add(new ArrayList<Card>());
        cols.add(new ArrayList<Card>());
        cols.add(new ArrayList<Card>());

    }

```

And then only will our individual "children classes" will assign new values for cardsLeft.

If we are to do this, I will also have to change my newGame function but that will only be a trivial task, really.

Let me know what you think.

**Comment by matsuish** [comment]
Seems nice. 
We are going to implement our class's constructor like this?

public EngGame(){
    super();
    cardsLeft = 52;
}

In Spanish and English game, score initialization is the same, so score could remain in Game() constructor.

**Comment by danielgwj** [comment]
yea thats the constructor that i have right now

and yea thats true that score can remain in the Game() constructor!

**Comment by danielgwj** [comment]
Spanish Game implemented!
