### ISSUE TITLE
English Game

### ISSUE THREAD

**Issue by matsuish** [cs361-W16/Group11-2#19]
@danielgwj 
Daniel, what are we going to do with Suit?
Making it interface or something?

**Comment by danielgwj** [comment]
We can leave it as it is for your part,
I will be adding the other suits in the suit class

```
public enum Suit  implements Serializable {
    Hearts, Spades, Diamonds, Clubs, Cups, Coins, Swords
}
```

Something like this. It won't affect your issue.

For the interface part, it will still show Hearts, Spades, Diamonds, and Clubs.
It will appear as Clubs, Cups, Coins, and Swords for me as I will be building my deck based on the Spanish suits.

```
// buildDeck for Spanish Game
    public void buildDeck() {
        for(int i = 1; i < 14; i++){
            if (i < 8 || i > 10) {
                deck.add(new Card(i, Suit.Clubs));
                deck.add(new Card(i, Suit.Cups));
                deck.add(new Card(i, Suit.Coins));
                deck.add(new Card(i, Suit.Swords));
            }
        }
    }
```

**Comment by matsuish** [comment]
Of course it should be like that!
I have no idea why I could not come up with that idea.
Thanks!

**Comment by danielgwj** [comment]
:+1:

**Comment by danielgwj** [comment]
@matsuish Something to note
In the latest changes, I have made the Game() class into an abstract class.
You will have to create a new English/AmericanGame() class

Just letting you know the changes are:
- buildDeck is already called when the super()
  (Something to look out for when your writing the tests)
- I have commented out most of the English Routes so you might want to check that place out

**Comment by matsuish** [comment]
Thanks!

**Comment by matsuish** [comment]
was it ok to add links to the other language games in each game page?

**Comment by danielgwj** [comment]
Totally fine!
