### ISSUE TITLE
Move Cards

### ISSUE THREAD

**Issue by jrotithor** [cs361-W16/Group11-2#4]
The move card function requires a text input. This is very easy to misuse, since anything can be entered into a text box, so this would need to be error checked. It needs to be changed to a drop-own menu for both the source and destination of the cards.

**Comment by danielgwj** [comment]
I think making it into a drop down menu would definitely help prevent the chances of mistyping

**Comment by danielgwj** [comment]
I believe this issue is solved, as the drop down menu works!
